### ISSUE TITLE
plugin is not installed

### ISSUE THREAD

**Issue by SilentGlasses** [byrnereese/mkdocs-minify-plugin#18]
Saw the comment for the [resolved issue](https://github.com/byrnereese/mkdocs-minify-plugin/issues/2) with the same problem, I am getting this after a fresh install.  I've tried changing plugin name with `-minify`, and `minify-plugin` just in case something was wrong on my end and it pulled an older version.

I'm running Python 3.10.5 on macOS Monterey 12.4 (21F79)

Please help..

```
pip install mkdocs-minify-plugin
Requirement already satisfied: mkdocs-minify-plugin
Requirement already satisfied: mkdocs>=1.0.4
Requirement already satisfied: htmlmin>=0.1.4
Requirement already satisfied: jsmin>=3.0.0
Requirement already satisfied: csscompressor>=0.9.5
Requirement already satisfied: mergedeep>=1.3.4
Requirement already satisfied: pyyaml-env-tag>=0.1
Requirement already satisfied: packaging>=20.5
Requirement already satisfied: importlib-metadata>=4.3
Requirement already satisfied: Jinja2>=2.10.2
Requirement already satisfied: ghp-import>=1.0
Requirement already satisfied: click>=3.3
Requirement already satisfied: PyYAML>=3.10
Requirement already satisfied: Markdown<3.4,>=3.2.1
Requirement already satisfied: watchdog>=2.0
Requirement already satisfied: python-dateutil>=2.8.1
Requirement already satisfied: zipp>=0.5
Requirement already satisfied: MarkupSafe>=2.0
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2
Requirement already satisfied: six>=1.5
```

```
pip3 list
Package                                   Version
----------------------------------------- -------
asyncio                                   3.4.3
Babel                                     2.10.3
click                                     8.1.3
csscompressor                             0.9.5
ghp-import                                2.1.0
gitdb                                     4.0.9
GitPython                                 3.1.27
htmlmin                                   0.1.12
importlib-metadata                        4.12.0
Jinja2                                    3.1.2
jsmin                                     3.0.1
Markdown                                  3.3.7
MarkupSafe                                2.1.1
mergedeep                                 1.3.4
mkdocs                                    1.3.1
mkdocs-git-revision-date-localized-plugin 1.1.0
mkdocs-material                           8.3.9
mkdocs-material-extensions                1.0.3
mkdocs-minify-plugin                      0.5.0
mkdocs-multirepo-plugin                   0.4.3
packaging                                 21.3
pip                                       22.2
Pygments                                  2.12.0
pymdown-extensions                        9.5
pyparsing                                 3.0.9
python-dateutil                           2.8.2
python-slugify                            6.1.2
pytz                                      2022.1
PyYAML                                    6.0
pyyaml_env_tag                            0.1
setuptools                                62.6.0
six                                       1.16.0
smmap                                     5.0.0
text-unidecode                            1.3
tqdm                                      4.64.0
watchdog                                  2.1.9
zipp                                      3.8.1
```

**Comment by wilhelmer** [comment]
Could you please share your `mkdocs.yml`? Thanks!

**Comment by SilentGlasses** [comment]
```
# Project information
site_name: Site Name
site_description: My Documentation Site
site_url: <site-url>
repo_url: <repo-url>
repo_name: Docs Repo

# Navigation
nav:
  - Home: index.md

# ↓↓ ---------------- DO NOT EDIT ANYTHING BELOW THIS LINE ---------------- ↓↓ #
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ #

theme:
  name: 'material'
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.integrate

  logo: 'images/logo.png'
  favicon: 'images/favicon.png'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'
  palette:
    primary: 'blue'
    accent: 'deep orange'
  icon:
    repo: fontawesome/brands/github
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

# Plugins
plugins:
  - search
  - autolinks
  - git-authors:
      exclude:
        - index.md
        - tags.md
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: true
      exclude:
        - index.md
        - tags.md
  - minify:
      minify_html: true
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: true
      use_pygments: true
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.pathconverter
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: false
      toc_depth: 4
```

**Comment by wilhelmer** [comment]
Hmm ... looks good to me. Maybe try to move the `- minify` entry up in the list, directly under `- search` to avoid interferences with other plugins.

Does the problem also occur with a clean MkDocs project? Try `mkdocs new my-project` and find a minimum reproducible version.

**Comment by SilentGlasses** [comment]
Ok, so moving it directly under `- search` works...

```
plugins:
  - search
  - minify:
      minify_html: true
```
