### ISSUE TITLE
Plugin has no apparent effect

### ISSUE THREAD

**Issue by juliangaal** [byrnereese/mkdocs-minify-plugin#28]
Hi, thanks for creating this plugin.

After adding it to my config

```
docs_dir: src
theme:
    name: material
    features:
      - navigation.instant
      - navigation.tabs
      - search.suggest
    plugins:
      - search:
          lang: #(1)!
            - de
            - en
      - exclude:
          glob:
            - "*sync-conflict*"
      - minify:
          minify_html: true
          htmlmin_opts:
              remove_comments: true
```

and building I see no apparent effect. The html files are not minimized and still contain whitespaces. How can I begin to debug this plugin?

**Setup**:
* Ubuntu 20.04
* mkdocs 1.4.2
