### ISSUE TITLE
Add support for glob syntax in `{css,js}_files` lists

### ISSUE THREAD

**Issue by sisp** [byrnereese/mkdocs-minify-plugin#35]
I'd like to be able to list files to minify using glob syntax, which doesn't seem to be supported yet. For instance:

```yaml
plugins:
  - minify:
      css_files:
        - assets/css/**/*.css
```

I have several CSS files, many contain page-specific styles, so the list grows with more pages. Instead of maintaining a hardcoded list of files, I'd prefer using glob syntax.

The same applies to JS files, of course.

WDYT?
